FROM python:3.12-alpine3.19

EXPOSE 8000
WORKDIR /backend

RUN apk add --no-cache postgresql15-dev gcc musl-dev fish git

ENV SHELL=/usr/bin/fish

COPY requirements.txt /backend/
COPY requirements-dev.txt /backend/

RUN pip install -r /backend/requirements.txt
RUN pip install -r /backend/requirements-dev.txt

ENTRYPOINT ["./entrypoint-dev.sh"]
