# Generated by Django 4.1.12 on 2023-11-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PLAYER_REG', 'Inscription joueur⋅euse'), ('MANAGER_REG', 'Inscription manager'), ('SUBSTITUTE_REG', 'Inscription remplaçant⋅e'), ('PIZZA', 'Pizza')], default='PIZZA', max_length=20, verbose_name='Catégorie de produit'),
        ),
    ]
