# Generated by Django 4.1.12 on 2023-11-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcount',
            options={'verbose_name': "Quantité d'un produit", 'verbose_name_plural': 'Quantités de produits'},
        ),
    ]
