# Generated by Django 4.1.12 on 2024-02-16 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
        ('payment', '0004_alter_product_desc_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='associated_timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.timeslot', verbose_name='Créneau associé'),
        ),
    ]
