# Generated by Django 4.1.12 on 2025-02-14 12:38

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0005_product_associated_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Réduction')),
                ('reason', models.CharField(max_length=200, verbose_name='Motif')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date de création')),
                ('used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('used_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Date d'utilisation")),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.product', verbose_name='Produit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réduction',
                'verbose_name_plural': 'Réductions',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='payment.discount', verbose_name='Réductions'),
        ),
    ]
