# Generated by Django 4.1.12 on 2025-10-16 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_migrate_tournaments'),
        ('payment', '0006_discount_transaction_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='associated_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.eventtournament', verbose_name='Tournoi associé'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=1024, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='intitulé'),
        ),
    ]
