# Generated by Django 4.1.12 on 2024-11-01 15:30

import django.core.validators
from django.db import migrations
import insalan.components.image_field


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=insalan.components.image_field.ImageField(blank=True, null=True, upload_to='profile-pictures', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp', 'avif'])], verbose_name='photo de profil'),
        ),
    ]
