# Generated by Django 4.1.12 on 2025-12-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('email_active', "L'utilisateur⋅rice a activé son courriel")], 'verbose_name': 'Utilisateur⋅rice', 'verbose_name_plural': 'Utilisateur⋅rice⋅s'},
        ),
        migrations.AddField(
            model_name='user',
            name='confirm_name',
            field=models.BooleanField(default=False, verbose_name='Ask to confirm name next time the user logs in'),
        ),
    ]
