"""
Django settings for insalan project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import json
from os import getenv, path
from pathlib import Path
from sys import argv

from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv(
    "DJANGO_SECRET",
    "django-insecure-&s(%0f90_a(wa!hk5w9pzri%+6%46)pjn4tq5xycvk9t7dwe_d",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(getenv("DEV", "0")) == 1

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
PROTOCOL = getenv("HTTP_PROTOCOL", "http")

OUTSIDE_PORT = getenv("NGINX_PORT", "80")
if (OUTSIDE_PORT == "80" and PROTOCOL == "http") or (OUTSIDE_PORT == "443" and PROTOCOL == "https"):
    OUTSIDE_PORT = "" # Don't specify it
else:
    OUTSIDE_PORT = f":{OUTSIDE_PORT}"

# LOGGING Setup
LOGGING = {
    "version":1,
    "disable_existing_loggers":False,
    "handlers":{
        "console":{
                "class":"logging.StreamHandler",
            },
        },
    "root": {
        "handlers": ["console"],
        "level": ["INFO", "DEBUG"][DEBUG]
        },
}

# Allow itself and the frontend
WEBSITE_HOST = getenv("WEBSITE_HOST", "localhost")
ALLOWED_HOSTS = [
    "api." + WEBSITE_HOST,
    WEBSITE_HOST,
    "dev." + WEBSITE_HOST,
    "gate." + WEBSITE_HOST,
]

CSRF_TRUSTED_ORIGINS = [
     PROTOCOL + "://api." + WEBSITE_HOST + OUTSIDE_PORT,
     PROTOCOL + "://" + WEBSITE_HOST + OUTSIDE_PORT,
     PROTOCOL + "://gate." + WEBSITE_HOST + OUTSIDE_PORT,
]

# Application definition

INSTALLED_APPS = [
    "insalan.apps.InsalanConfig",
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "insalan.user",
    "insalan.partner",
    "insalan.tournament",
    "insalan.tickets",
    "insalan.cms",
    "insalan.payment",
    "insalan.pizza",
    "drf_yasg",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

SWAGGER_SETTINGS = {
    "USE_SESSION_AUTH": True,
    "LOGIN_URL": "/v1/user/login/",
    "LOGOUT_URL": "/v1/user/logout/",
}

ROOT_URLCONF = "insalan.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "insalan.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "USER": getenv("DB_USER", "user") + ("_test" if "test" in argv else ""),
        "NAME": getenv("DB_NAME", "mydb"),
        "PASSWORD": getenv("DB_PASS", "password"),
        "HOST": getenv("DB_HOST", "localhost"),
        "PORT": getenv("DB_PORT", "5432"),
    },
    "cms": {
        "ENGINE": 'djongo',
        "NAME": "cms-db",
        "CLIENT": {
            "password": getenv("MONGODB_PASS", "password"),
            "host": getenv("DB_HOST", "localhost"),
            "port": getenv("DB_MONGO_PORT", "5433"),
            "username": getenv("MONGODB_USER", "admin")
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "user.User"

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

TIME_ZONE = "Europe/Paris"

LANGUAGE_CODE = 'fr'
LOCALE_PATH='locale'
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ("en", _("Anglais")),
    ("fr", _("Français")),
    ("es", _("Espagnol")),
    ("de", _("Allemand")),
]

LOCALE_PATHS = [path.join(BASE_DIR, 'locale')]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/v1/static/" # https://stackoverflow.com/a/73631136
STATIC_ROOT = "v1/" + getenv("STATIC_ROOT", "static/")
STATICFILES_DIRS = [path.join(BASE_DIR, "assets")]

MEDIA_URL = 'v1/media/'
MEDIA_ROOT = 'v1/' + getenv("MEDIA_ROOT", "media/")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
    "DEFAULT_RENDERER_CLASSES": (
        'rest_framework.renderers.JSONRenderer',
    )
}

# Login and logout
LOGIN_URL = ("rest_framework:login",)
LOGIN_REDIRECT_URL = "/v1/"
LOGOUT_URL = "rest_framework:logout"

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://" + getenv("WEBSITE_HOST", "localhost"),
    "https://api." + getenv("WEBSITE_HOST", "localhost"),
    "http://" + getenv("WEBSITE_HOST", "localhost"),
    "http://api." + getenv("WEBSITE_HOST", "localhost"),
    "https://" + getenv("HELLOASSO_HOSTNAME", "localhost"), # helloasso has be to trusted
    "http://gate." + getenv("WEBSITE_HOST", "localhost"),
    "https://gate." + getenv("WEBSITE_HOST", "localhost"),

]
CSRF_COOKIE_DOMAIN = '.' + getenv("WEBSITE_HOST", "localhost")
# MAILER SETTINGS - Mail are not sent with test mode
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# pylint: disable-next=line-too-long
EMAIL_AUTH = json.loads(getenv("MAIL_AUTH", '{"contact": {"from":"noreply@insalan.fr", "pass":"password", "host":"localhost", "port":587, "ssl":true}, "tournament": {"from":"noreply@insalan.fr", "pass":"password", "host":"localhost", "port":587, "ssl":true}}'))
EMAIL_SUBJECT_PREFIX = "[InsaLan] "

# Payment variables
HA_URL = f"https://{format(getenv('HELLOASSO_HOSTNAME', 'api.helloasso-sandbox.com'))}"
HA_ORG_SLUG = getenv("HELLOASSO_ORGANIZATION_SLUG", "insalan-test")
# View URLs (fall back on the front page if needed)
HA_RETURN_URL = getenv("HELLOASSO_RETURN_URL", f"https://{WEBSITE_HOST}/")
HA_ERROR_URL = getenv("HELLOASSO_ERROR_URL", f"https://{WEBSITE_HOST}/")
HA_BACK_URL = getenv("HELLOASSO_BACK_URL", f"https://{WEBSITE_HOST}/")
# OAuth Credentials
HA_OAUTH_CLIENT_SECRET = getenv("HELLOASSO_CLIENT_SECRET")
HA_OAUTH_CLIENT_ID = getenv("HELLOASSO_CLIENT_ID")

RIOT_API_KEY = getenv("RIOT_API_KEY", "RGAPI-00000000-0000-0000-0000-000000000000")

# Session cookie settings
SESSION_COOKIE_AGE = int(getenv("SESSION_COOKIE_AGE", "1209600"))

# Unfold admin panel settings
UNFOLD = {
    "SITE_TITLE": "InsaLan",
    "SITE_HEADER": "Administration InsaLan",
    "SITE_ICON": {
        "light": lambda request: static("images/logo_retro_black.png"),  # light mode
        "dark": lambda request: static("images/logo_retro_white.png"),  # dark mode
    },
    "SITE_URL": PROTOCOL + "://" + WEBSITE_HOST,
    "BORDER_RADIUS": "10px",
    # So our old ass version of Unfold (due to our old ass version of Django) doesn't support oklch
    # "COLORS": {
    #     "primary": {
    #         "50": "oklch(98.7% .0078 228.0)",
    #         "100": "oklch(96.2% .0250 228.0)",
    #         "200": "oklch(91.3% .0578 228.0)",
    #         "300": "oklch(84.4% .1062 228.0)",
    #         "400": "oklch(77.7% .1578 228.0)",
    #         "500": "oklch(69.2% .1765 228.0)",
    #         "600": "oklch(60.0% .1531 228.0)",
    #         "700": "oklch(51.1% .1312 228.0)",
    #         "800": "oklch(40.0% .1015 228.0)",
    #         "900": "oklch(29.2% .0750 228.0)",
    #         "950": "oklch(18.4% .0468 228.0)",
    #     },
    # },
    "COLORS": { # Generated on https://www.tailwindshades.com
        "base": {
            50: '#F2F2F2',
            100: '#E6E6E6',
            200: '#CCCCCC',
            300: '#B3B3B3',
            400: '#999999',
            500: '#808080',
            600: '#666666',
            700: '#4D4D4D',
            800: '#333333',
            900: '#1A1A1A',
            950: '#0D0D0D'
        },
        "primary": {
            50: '#F0FAFF',
            100: '#DBF4FF',
            200: '#B3E8FF',
            300: '#8ADCFF',
            400: '#61D0FF',
            500: '#29BFFF',
            600: '#00A8F0',
            700: '#0081B8',
            800: '#005980',
            900: '#003247',
            950: '#001E2B'
        },
    },
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
    }
}
