# Generated by Django 4.1.12 on 2025-12-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0019_alter_player_options_alter_substitute_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Ville de départ depuis laquelle le voyage est effectué.', max_length=255, verbose_name='Ville de départ')),
                ('transportation_method', models.CharField(choices=[('BIKE', 'Vélo'), ('BUS', 'Bus'), ('BOAT', 'Bateau'), ('CAR', 'Voiture'), ('CARPOOLING', 'Covoiturage'), ('NONE', 'Aucun'), ('PLANE', 'Avion'), ('PUBLIC_TRANSPORT', 'Transport public urbain'), ('TRAIN', 'Train')], help_text="Mode de transport utilisé pour se rendre à l'évènement.", max_length=16, verbose_name='Mode de transport')),
                ('event', models.ForeignKey(help_text='Évènement pour lequel le déplacement est effectué.', on_delete=django.db.models.deletion.CASCADE, to='tournament.event', verbose_name='Évènement')),
            ],
            options={
                'verbose_name': 'Information de déplacement',
                'verbose_name_plural': 'Informations de déplacement',
            },
        ),
    ]
