# Generated by Django 4.1.12 on 2023-11-29 14:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_alter_product_category'),
        ('tickets', '0003_initial'),
        ('tournament', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='pseudo',
            new_name='name_in_game',
        ),
        migrations.AddField(
            model_name='game',
            name='players_per_team',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of players per team'),
        ),
        migrations.AddField(
            model_name='game',
            name='substitute_players_per_team',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of substitute players per team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Description du tournoi'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='substitute_online_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_product_reference', to='payment.product', verbose_name='Produit substitute'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='substitute_price_online',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='prix manager en ligne'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='substitute_price_onsite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='prix manager sur place'),
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(blank=True, choices=[('NOTPAID', 'Pas payé'), ('PAID', 'Payé'), ('LATER', 'Payera sur place')], default='NOTPAID', max_length=10, verbose_name='Statut du paiement')),
                ('name_in_game', models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Pseudo en jeu')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.team', verbose_name='Équipe')),
                ('ticket', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticket', verbose_name='Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur⋅ice')),
            ],
            options={
                'verbose_name': "Inscription d'un⋅e remplaçant⋅e",
                'verbose_name_plural': 'Inscriptions de remplaçant⋅es',
            },
        ),
        migrations.CreateModel(
            name='Caster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42, verbose_name='Nom du casteur')),
                ('image', models.FileField(blank=True, null=True, upload_to='profile-pictures', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Photo de profil')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Lien twitch ou autre')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament', verbose_name='Tournoi')),
            ],
        ),
        migrations.AddConstraint(
            model_name='substitute',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='not_twice_same_substitute'),
        ),
    ]
