# Generated by Django 4.1.12 on 2023-11-19 00:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pseudo',
            field=models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Pseudo en jeu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)], verbose_name="Mot de passe de l'équipe"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='maxTeam',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre maximal d'équipe"),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur⋅ice'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur⋅ice'),
        ),
    ]
