# Generated by Django 4.1.12 on 2023-11-29 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_rename_pseudo_player_name_in_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caster',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile-pictures', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp'])], verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='event-icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp'])], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='tournament-icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp'])], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='substitute_price_online',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='prix Remplaçant en ligne'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='substitute_price_onsite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='prix Remplaçant sur place'),
        ),
    ]
