# Generated by Django 4.1.12 on 2024-02-03 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_team_captain_tournament_planning'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentMailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_validated', models.BooleanField(blank=True, default=False, verbose_name="Filtre d'équipe validée")),
                ('captains', models.BooleanField(blank=True, default=False, verbose_name='Filtre de capitaines')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Titre du mail')),
                ('content', models.TextField(blank=True, default='', max_length=50000, verbose_name='Contenu du mail')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='mail-attachments', verbose_name='Pièce jointe')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.tournament', verbose_name='Tournoi')),
            ],
            options={
                'verbose_name_plural': 'mailers',
            },
        ),
    ]
