# Generated by Django 4.1.12 on 2024-02-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournamentmailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmailer',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Mail'),
        ),
        migrations.AddField(
            model_name='tournamentmailer',
            name='number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Nombre de mails dans la file'),
        ),
    ]
