# Generated by Django 4.1.12 on 2024-11-01 15:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import insalan.components.image_field


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_alter_group_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name='Position horizontale')),
                ('y', models.IntegerField(verbose_name='Position verticale')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.AlterField(
            model_name='caster',
            name='image',
            field=insalan.components.image_field.ImageField(blank=True, null=True, upload_to='profile-pictures', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp', 'avif'])], verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=insalan.components.image_field.ImageField(blank=True, null=True, upload_to='event-icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp', 'avif'])], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=insalan.components.image_field.ImageField(blank=True, null=True, upload_to='tournament-icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp', 'avif'])], verbose_name='Logo'),
        ),
        migrations.CreateModel(
            name='SeatSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.ManyToManyField(to='tournament.seat', verbose_name='Place')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament', verbose_name='Tournoi')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.event', verbose_name='Évènement'),
        ),
        migrations.AddField(
            model_name='team',
            name='seat_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.seatslot', verbose_name='Slot'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('event', 'x', 'y'), name='one_seat_per_position_per_event'),
        ),
    ]
