# Generated by Django 4.1.12 on 2024-11-21 22:01

import django.core.validators
from django.db import migrations
import insalan.components.image_field


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_seat_alter_caster_image_alter_event_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=insalan.components.image_field.ImageField(blank=True, null=True, upload_to='event-posters', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp', 'avif'])], verbose_name='Affiche'),
        ),
    ]
