# Generated by Django 4.1.12 on 2025-01-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_event_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description_bottom',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Description du tournoi en bas de page'),
        ),
    ]
