# Generated by Django 4.1.12 on 2025-02-14 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_tournament_description_bottom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='planning',
        ),
        migrations.AddField(
            model_name='event',
            name='planning_file',
            field=models.FileField(blank=True, null=True, upload_to='event-planning', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ics'])], verbose_name='Fichier ICS du planning'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='planning_file',
            field=models.FileField(blank=True, null=True, upload_to='tournament-planning', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ics'])], verbose_name='Fichier ICS du planning'),
        ),
    ]
