# Generated by Django 4.1.12 on 2025-03-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_remove_tournament_planning_event_planning_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swissmatch',
            name='score_group',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='seed',
            field=models.PositiveIntegerField(default=0, verbose_name='Seed'),
        ),
        migrations.AlterField(
            model_name='group',
            name='round_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de rounds'),
        ),
        migrations.AlterField(
            model_name='seeding',
            name='seeding',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='swissseeding',
            name='seeding',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournament.tournament', verbose_name='Tournoi'),
        ),
        migrations.CreateModel(
            name='GroupTiebreakScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Score de tiebreak')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.group')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.team')),
            ],
            options={
                'verbose_name': "Score de tiebreak d'une équipe dans une poule",
            },
        ),
    ]
