# Generated by Django 4.1.12 on 2025-03-09 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_swissmatch_score_group_team_seed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=512, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nom du tournoi'),
        ),
    ]
