# Generated by Django 4.1.12 on 2025-10-16 18:15

from django.db import migrations
from django.contrib.contenttypes.models import ContentType

def migrate_tournaments(apps, schema_editor):
    Tournament = apps.get_model('tournament', 'Tournament')
    EventTournament = apps.get_model('tournament', 'EventTournament')

    db_alias = schema_editor.connection.alias
    
    EventCT = ContentType.objects.get_for_model(EventTournament)

    for t in Tournament.objects.using(db_alias).all():
        
        EventTournament.objects.using(db_alias).create(
            id=t.id,
            name=t.name,
            game_id=t.game.id,
            rules=t.rules,
            logo=t.logo,
            maxTeam=t.maxTeam,
            description=t.description,
            description_bottom=t.description_bottom,

            event_id=t.event.id,
            is_announced=t.is_announced,
            registration_open=t.registration_open,
            registration_close=t.registration_close,
            player_price_online=t.player_price_online,
            player_price_onsite=t.player_price_onsite,
            manager_price_online=t.manager_price_online,
            manager_price_onsite=t.manager_price_onsite,
            substitute_price_online=t.substitute_price_online,
            substitute_price_onsite=t.substitute_price_onsite,
            cashprizes=t.cashprizes,
            manager_online_product_id=(t.manager_online_product.id if t.manager_online_product else None),
            substitute_online_product_id=(t.substitute_online_product.id if t.substitute_online_product else None),
            player_online_product_id=(t.player_online_product.id if t.player_online_product else None),
            planning_file=t.planning_file,
            polymorphic_ctype_id=EventCT.id,
        )

def reverse_migration(apps, schema_editor):
    raise RuntimeError("Cannot reverse this migration")

class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_basetournament_remove_tournament_event_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_tournaments, reverse_migration),
    ]
