# Generated by Django 4.1.12 on 2025-10-16 18:07

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_tournament'),
        ('tournament', '0017_migrate_tournaments'),
        ('payment', '0007_alter_product_associated_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.basetournament', verbose_name='Tournoi'),
        ),
        migrations.AlterField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.basetournament', verbose_name='Tournoi'),
        ),
        migrations.AlterField(
            model_name='swissround',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.basetournament', verbose_name='Tournoi'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournament.basetournament', verbose_name='Tournoi'),
        ),migrations.AlterField(
            model_name='caster',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.eventtournament', verbose_name='Tournoi'),
        ),
        migrations.AlterField(
            model_name='seatslot',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.eventtournament', verbose_name='Tournoi'),
        ),
        migrations.AlterField(
            model_name='tournamentmailer',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.eventtournament', verbose_name='Tournoi'),
        ),
        migrations.AddIndex(
            model_name='eventtournament',
            index=models.Index(fields=['event'], name='tournament__event_i_6be6db_idx'),
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
