# Generated by Django 4.1.12 on 2025-12-05 20:58

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0018_delete_tournament_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': "Inscription d'un⋅e joueur⋅euse", 'verbose_name_plural': 'Inscription de joueur⋅euse⋅s'},
        ),
        migrations.AlterModelOptions(
            name='substitute',
            options={'verbose_name': "Inscription d'un⋅e remplaçant⋅e", 'verbose_name_plural': 'Inscriptions de remplaçant⋅e⋅s'},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='tournament__year_450f04_idx',
        ),
        migrations.RemoveField(
            model_name='basetournament',
            name='maxTeam',
        ),
        migrations.RemoveField(
            model_name='event',
            name='month',
        ),
        migrations.RemoveField(
            model_name='event',
            name='year',
        ),
        migrations.AddField(
            model_name='basetournament',
            name='current_threshold_index',
            field=models.IntegerField(default=0, verbose_name='Index du seuil actuel'),
        ),
        migrations.AddField(
            model_name='basetournament',
            name='max_team_thresholds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]), default=list, help_text='Liste croissante de seuils (ex: [24, 32, 40])', size=None, verbose_name="Seuils du nombre d'équipes"),
        ),
        migrations.AddField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_start',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='eventtournament',
            name='enable_manager',
            field=models.BooleanField(default=True, verbose_name='Activer les places manager'),
        ),
        migrations.AddField(
            model_name='manager',
            name='ecological_data_sent',
            field=models.BooleanField(default=False, verbose_name='Données écologique envoyées'),
        ),
        migrations.AddField(
            model_name='player',
            name='ecological_data_sent',
            field=models.BooleanField(default=False, verbose_name='Données écologique envoyées'),
        ),
        migrations.AddField(
            model_name='player',
            name='validator_data',
            field=models.JSONField(blank=True, default=dict, help_text='Données additionnelles fournies par le validateur de pseudo en jeu.', null=True, verbose_name='Données additionnelles'),
        ),
        migrations.AddField(
            model_name='substitute',
            name='ecological_data_sent',
            field=models.BooleanField(default=False, verbose_name='Données écologique envoyées'),
        ),
        migrations.AddField(
            model_name='substitute',
            name='validator_data',
            field=models.JSONField(blank=True, default=dict, help_text='Données additionnelles fournies par le validateur de pseudo en jeu.', null=True, verbose_name='Données additionnelles'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ongoing',
            field=models.BooleanField(default=True, help_text="Détermine si l'évènement est affiché sur la page principale", verbose_name='En cours'),
        ),
        migrations.AlterField(
            model_name='game',
            name='validators',
            field=models.CharField(choices=[('None', 'Pas de Validation de nom'), ('FaceIt', 'Validation FaceIt'), ('LoL', 'Validation League of Legends')], default='None', max_length=42, verbose_name='Validateurs de pseudo'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur⋅rice'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur⋅rice'),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur⋅rice'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date_start'], name='tournament__date_st_568b5b_idx'),
        ),
    ]
