# Generated by Django 4.1.12 on 2026-01-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_alter_player_options_alter_substitute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetournament',
            name='api_data',
            field=models.JSONField(blank=True, default=dict, help_text="Données JSON pour l'automatisation des matchs", null=True, verbose_name='Données API'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_processor',
            field=models.CharField(choices=[('None', 'Pas de gestion automatique'), ('LoL', 'League of Legends')], default='None', max_length=42, verbose_name='Récupération des matchs'),
        ),
        migrations.AddField(
            model_name='game',
            name='games_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Paramètres JSON pour la configuration des API (ex: map pour LoL)', null=True, verbose_name='Paramètres du jeu'),
        ),
        migrations.AddField(
            model_name='match',
            name='api_data',
            field=models.JSONField(blank=True, default=dict, help_text="Données JSON pour l'automatisation du match", null=True, verbose_name='Données API'),
        ),
    ]
