# Generated by Django 4.1.12 on 2026-03-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_basetournament_api_data_game_game_processor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Nom de la phase')),
                ('index', models.PositiveIntegerField(default=1, verbose_name='Index de la phase')),
            ],
            options={
                'verbose_name': "Phase d'un tournoi",
                'verbose_name_plural': "Phases d'un tournoi",
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='play_all',
            field=models.BooleanField(default=False, verbose_name='Jouer toutes les parties'),
        ),
        migrations.AddField(
            model_name='swissround',
            name='name',
            field=models.CharField(default='Ronde suisse', max_length=40, verbose_name='Nom de la ronde suisse'),
        ),
        migrations.AddField(
            model_name='swissround',
            name='round_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de tour'),
        ),
        migrations.AlterField(
            model_name='seeding',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.team'),
        ),
        migrations.AlterField(
            model_name='swissround',
            name='min_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Score minimal pour la qualification'),
        ),
        migrations.AlterField(
            model_name='swissseeding',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.team'),
        ),
        migrations.AddConstraint(
            model_name='swissround',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('min_score__isnull', True), _negated=True), models.Q(('round_count__isnull', True), _negated=True), _connector='XOR'), name='either_min-score_or_round-count', violation_error_message='Soit le score minimal,                 soit le nombre de round doit être renseigné'),
        ),
        migrations.AddField(
            model_name='stage',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.basetournament', verbose_name='Tournoi'),
        ),
        migrations.AddField(
            model_name='bracket',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.stage', verbose_name='Phase du tournoi'),
        ),
        migrations.AddField(
            model_name='group',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.stage', verbose_name='Phase du tournoi'),
        ),
        migrations.AddField(
            model_name='swissround',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.stage', verbose_name='Phase du tournoi'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['tournament'], name='tournament__tournam_c79849_idx'),
        ),
    ]
