# Generated by Django 4.1.12 on 2025-10-16 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_migrate_tournaments'),
        ('tickets', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.eventtournament', verbose_name='Tournoi'),
        ),
    ]
