# Generated by Django 4.1.12 on 2024-02-16 09:33

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0004_alter_product_desc_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200, verbose_name='Utilisateur')),
                ('payment_method', models.CharField(choices=[('CB', 'Carte'), ('CH', 'Chèque'), ('ES', 'Espèces'), ('LI', 'Lyfpay')], default='CB', max_length=2, verbose_name='Moyen de paiement')),
                ('price', models.FloatField(verbose_name='Prix')),
                ('paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('delivered', models.BooleanField(default=False, verbose_name='Livrée')),
                ('delivery_date', models.DateField(default=None, null=True, verbose_name='Date de livraison')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la pizza')),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='Ingrédient'), blank=True, null=True, size=None, verbose_name='Ingrédients')),
                ('allergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='Allergène'), blank=True, null=True, size=None, verbose_name='Allergènes')),
                ('image', models.FileField(blank=True, null=True, upload_to='pizzas', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp'])], verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateTimeField(verbose_name='Heure de livraison')),
                ('start', models.DateTimeField(verbose_name='Début des commandes')),
                ('end', models.DateTimeField(verbose_name='Fin des commandes')),
                ('pizza_max', models.IntegerField(verbose_name='Nombre maximum de pizzas')),
                ('public', models.BooleanField(default=True, verbose_name='Créneau ouvert à tous')),
                ('ended', models.BooleanField(default=False, verbose_name='Créneau terminé')),
                ('player_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Prix pour les joueurs')),
                ('staff_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Prix pour les staffs')),
                ('external_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Prix pour les externes')),
                ('external_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_pizza_product_reference', to='payment.product', verbose_name='Produit pour les externes')),
                ('pizza', models.ManyToManyField(related_name='pizzas', to='pizza.pizza', verbose_name='Pizzas disponibles')),
                ('player_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_pizza_product_reference', to='payment.product', verbose_name='Produit pour les joueurs')),
                ('staff_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_pizza_product_reference', to='payment.product', verbose_name='Produit pour les staffs')),
            ],
            options={
                'verbose_name': 'Créneau de commande',
                'verbose_name_plural': 'Créneaux de commande',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.order')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('orders', models.ManyToManyField(related_name='orders', to='pizza.order', verbose_name='Commandes')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.timeslot', verbose_name='Créneau de commande')),
            ],
            options={
                'verbose_name': 'Export de pizza',
                'verbose_name_plural': 'Exports de pizza',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ManyToManyField(related_name='pizza_order', through='pizza.PizzaOrder', to='pizza.pizza', verbose_name='Pizzas commandées'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.timeslot', verbose_name='Créneau de commande'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur du site'),
        ),
    ]
