# Generated by Django 4.1.12 on 2024-03-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CB', 'Carte bancaire'), ('CH', 'Chèque'), ('ES', 'Espèces'), ('LI', 'Lyfpay'), ('FR', 'Gratuit')], default='CB', max_length=2, verbose_name='Moyen de paiement'),
        ),
    ]
