# Generated by Django 4.1.12 on 2024-11-01 15:30

import django.core.validators
from django.db import migrations
import insalan.components.image_field


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=insalan.components.image_field.ImageField(blank=True, null=True, upload_to='pizzas', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp', 'avif'])], verbose_name='Image'),
        ),
    ]
