# Generated by Django 4.1.12 on 2023-11-21 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du partenaire/sponsor')),
                ('url', models.URLField(verbose_name='URL')),
                ('logo', models.FileField(upload_to='partners', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Logo')),
                ('partner_type', models.CharField(choices=[('PA', 'Partenaire'), ('SP', 'Sponsor')], default='PA', max_length=2, verbose_name='Type de partenariat')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
            },
        ),
    ]
