# Generated by Django 4.1.6 on 2023-02-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('logo', models.ImageField(upload_to='static/partners')),
                ('type', models.CharField(choices=[('PA', 'Partner'), ('SP', 'Sponsor')], default='PA', max_length=2)),
            ],
        ),
    ]
