# Generated by Django 4.1.6 on 2023-02-27 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('url', models.URLField()),
                ('logo', models.FileField(upload_to='static/partners', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])])),
                ('partner_type', models.CharField(choices=[('PA', 'Partenaire'), ('SP', 'Sponsor')], default='PA', max_length=2, verbose_name='Type')),
            ],
        ),
    ]
