# Generated by Django 4.1.12 on 2024-11-01 15:30

import django.core.validators
from django.db import migrations
import insalan.components.image_field


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_alter_partner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=insalan.components.image_field.ImageField(upload_to='partners', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp', 'avif'])], verbose_name='Logo'),
        ),
    ]
