# Generated by Django 4.1.12 on 2023-11-21 20:09

from django.db import migrations, models
import insalan.cms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la constante')),
                ('value', models.CharField(max_length=200, verbose_name='Valeur de la constante')),
            ],
            options={
                'verbose_name': 'Constante',
                'verbose_name_plural': 'Constantes',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du contenu')),
                ('content', models.TextField(validators=[insalan.cms.models.constant_definition_validator], verbose_name='Contenu')),
            ],
            options={
                'verbose_name': 'Contenu',
                'verbose_name_plural': 'Contenus',
            },
        ),
    ]
