# Generated by Django 4.1.12 on 2024-01-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='planning',
            field=models.BooleanField(default=False, help_text='Si oui, les couleurs seront modifiées pour correspondre au site web.', verbose_name='Est-ce que ce contenu est un planning exporté depuis un gsheet ?'),
        ),
    ]
