# Generated by Django 4.1.12 on 2025-02-14 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_content_planning'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Le nom du fichier ne doit pas contenir les symboles [ et ]', regex='^[^[\\]]*$')], verbose_name='Nom du fichier')),
                ('file', models.FileField(upload_to='files/', verbose_name='Fichier')),
            ],
            options={
                'verbose_name': 'Fichier',
                'verbose_name_plural': 'Fichiers',
            },
        ),
        migrations.RemoveField(
            model_name='content',
            name='planning',
        ),
        migrations.AlterField(
            model_name='constant',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Le nom de la constante ne doit pas contenir les symboles { et }', regex='^[^{}]*$')], verbose_name='Nom de la constante'),
        ),
    ]
